#!/bin/sh

[ -z "$DOTFILESDIR" ] && DOTFILESDIR=${HOME}/dotfiles
FILES="bash_login bashrc gdbinit gitconfig irssi/config muttrc screenrc"
FILES="$FILES ssh/config subversion/config vimrc xinitrc"

usage()
{
    echo "Usage: $(basename ${0}) [ -f ]" 1>&2
    exit 1
}

if [ $# -gt 1 ] || [ $# -eq 1 -a "$1" != '-f' ]; then
    usage
fi

for file in $FILES ; do
    case $file in
    muttrc)
        mkdir -p ${HOME}/.mutt/cache
        ;;
    irssi/*)
        mkdir -p ${HOME}/.irssi
        ;;
    subversion/*)
        mkdir -p ${HOME}/.subversion
        ;;
    esac
    ln -s $1 ${DOTFILESDIR}/$file ${HOME}/.$file
done
