#!/bin/sh

[ -z "$DOTFILESDIR" ] && DOTFILESDIR=${HOME}/dotfiles
FILES="bash_aliases bash_login bashrc gdbinit gitconfig irssi/config"
FILES="$FILES mergemasterrc muttrc screenrc ssh/config subversion/config"
FILES="$FILES vimrc xinitrc"

usage()
{
    cat >&2 <<__EOF__ 
Usage: $(basename ${0}) [ -f ]

Options:
  -f            -- Force existing files to be overwritten.
__EOF__
    exit ${1-1}
}

if [ $# -gt 1 ] || [ $# -eq 1 -a "$1" != '-f' ]; then
    usage
fi

for file in $FILES ; do
    case $file in
    muttrc)
        mkdir -p ${HOME}/.mutt/cache
        ;;
    irssi/*)
        mkdir -p ${HOME}/.irssi
        ;;
    subversion/*)
        mkdir -p ${HOME}/.subversion
        ;;
    esac
    ln -s $1 ${DOTFILESDIR}/$file ${HOME}/.$file
done
