#!/bin/sh

[ -z "$DOTFILESDIR" ] && DOTFILESDIR=${HOME}/dotfiles

FILES="
bash_aliases
bash_login
bashrc
gdbinit
gitconfig
gitignore
irssi/config
mergemasterrc
muttrc
rtorrent.rc
screenrc
ssh/config
subversion/config
tmux.conf
vimrc
xinitrc
"

usage()
{
    cat >&2 <<__EOF__
Usage: $(basename ${0}) [ -f ]

Options:
  -f            -- Force existing files to be overwritten.
__EOF__
    exit ${1-1}
}

if [ $# -gt 1 ] || [ $# -eq 1 -a "$1" != '-f' ]; then
    usage
fi

for file in $FILES ; do
    if expr $file : '[a-zA-Z][a-zA-Z]*/' >/dev/null 2>&1; then
        mkdir -p ${HOME}/.${file%%/*}
    fi
    case $file in
    muttrc)
        mkdir -p ${HOME}/.mutt/cache
        ;;
    esac
    ln -s $1 ${DOTFILESDIR}/$file ${HOME}/.$file
done
