#!/bin/sh


[ -z "$DOTFILESDIR" ] && DOTFILESDIR=${HOME}/dotfiles
FILES="bashrc gitconfig muttrc screenrc vimrc xinitrc"

usage() {
	echo "usage: $(basename ${0}) < cmp | install | merge > [ file ]"
	exit 1
}

run() {
	for file in $FILES; do
		[ -n "$2" -a ${file} != "$2" ] && continue
		eval "$1"
	done
}

[ $# -ne 1 -a $# -ne 2 ] && usage

case $1 in
cmp)
	run 'diff ${DOTFILESDIR}/${file} ${HOME}/.${file}' $2
	;;
install)
	run 'cp -f ${DOTFILESDIR}/${file} ${HOME}/.${file}' $2
	;;
merge)
	run 'cp -f ${HOME}/.${file} ${DOTFILESDIR}/${file}' $2
	;;
*)
	usage
	;;
esac
