#!/bin/sh


[ -z "$DOTFILESDIR" ] && DOTFILESDIR=${HOME}/dotfiles
FILES="bashrc gitconfig muttrc screenrc vimrc xinitrc"

usage() {
	echo "usage: $(basename ${0}) < cmp | install | merge >"
	exit 1
}

run() {
	local ret

	ret=0
	for file in $FILES; do
		eval "$1"
		[ $? -ne 0 ] && ret=1
	done
	return $ret
}

cmpfiles() {
	run 'cmp ${DOTFILESDIR}/${file} ${HOME}/.${file}'
	return $?
}

installfiles() {
	cmpfiles && run 'cp -f ${DOTFILESDIR}/${file} ${HOME}/.${file}'
}

mergefiles() {
	run 'cp -f ${HOME}/.${file} ${DOTFILESDIR}/${file}'
}

[ $# -ne 1 ] && usage

case $@ in
cmp)
	cmpfiles
	;;
install)
	installfiles
	;;
merge)
	mergefiles
	;;
*)
	usage
	;;
esac
