#!/bin/sh

[ -z "$DOTFILESDIR" ] && DOTFILESDIR=${HOME}/dotfiles
FILES="bash_login bashrc gdbinit gitconfig muttrc screenrc vimrc xinitrc"

usage() {
    echo "usage: $(basename ${0}) < cmp | install | merge > [ file ]"
    exit 1
}

run() {
    local ran

    ran=0
    for file in $FILES; do
        [ -n "$2" -a ${file} != "$2" ] && continue
        eval "$1"
        ran=1
    done

    [ $ran -eq "0" ] && echo "$(basename ${0}): no dotfile '$2'" && exit 1
}

[ $# -ne 1 -a $# -ne 2 ] && usage

case $1 in
cmp)
    run 'diff $DOTFILESDIR/$file $HOME/.$file' $2 2>/dev/null
    ;;
install)
    [ -d $HOME/bin ] && [ ! -x $HOME/bin/manage-dotfiles ] && \
        ln -s $DOTFILESDIR/manage $HOME/bin/manage-dotfiles
    run 'cmp -s $DOTFILESDIR/$file $HOME/.$file || echo $file' $2
    run '[ -f $DOTFILESDIR/$file ] && cp -f $DOTFILESDIR/$file $HOME/.$file' $2
    ;;
merge)
    run 'cmp -s $DOTFILESDIR/$file $HOME/.$file || echo $file' $2
    run '[ -f $HOME/.$file ] && cp -f $HOME/.$file $DOTFILESDIR/$file' $2
    ;;
*)
    usage
    ;;
esac
